### ISSUE TITLE
Scrape reviews

### ISSUE THREAD

**Issue by twigbranch** [chadrem/market_bot#21]
Is there any support for scraping reviews?  If not, please consider this a feature request.

**Comment by cawel** [comment]
I see that it is not possible to get the reviews from an app. Since you are scraping HTML, that is no surprise, because from a quick investigation I can see in my browser that the reviews on the Google Play website are retrieved with some on-demand JS via an XHR request with some authentication (I see a token in the POST body).

Do you have more info (or s a link) which would help us understand the details of retrieving the reviews?

**Comment by chadrem** [comment]
@cawel No I do not have any info and market_bot doesn't support app reviews at this time.  Please send me a pull request if you decide to build it as I'm sure others are interested in the feature.  I can put you in touch with a commercial vendor if you are looking to pay for the data.  Shoot me an email if you are.

**Comment by cawel** [comment]
Thanks for the quick reply. I will investigate further how to fetch reviews then. 

By the way, I noticed you are often mentioning the commercial vendor option (e.g. twice in this thread, in the readme). Would you have an interest in it? :)
