### ISSUE TITLE
Error on running Bot under Windows

### ISSUE THREAD

**Issue by gowthamgts** [chadrem/market_bot#39]
I've the following error when using a single `require 'market-bot'` statement:

![capture](https://cloud.githubusercontent.com/assets/4407260/7901848/13c6581a-07bb-11e5-94fa-27f3332349ed.PNG)

Some `curl` problem.

**Comment by chadrem** [comment]
@gowthamgts The market_bot gem relies on the Typhoeus gem for HTTP requests.  Your problem is most likely with that gem and not market_bot.  I recommend first getting the Typhoeus gem working and then trying market_bot again.  It's possible the problem is that you just need to install curl.  It looks like you are running market_bot on Windows.  I have never tested it on Windows so you may have an easier time getting it to work using a Linux virtual machine.

**Comment by gowthamgts** [comment]
Yeah, on windows and I googled and already installed the gem using `gem install typhoeus` but same error.

**Comment by chadrem** [comment]
Did you install curl?   Have you verified the libcurl shared library exists on your system? 

  -Chad

**Comment by gowthamgts** [comment]
@chadrem Yeah I got installed curl already but `libcurl` was missing and running the same program resulted in a SSL related error. :disappointed: 

![capture](https://cloud.githubusercontent.com/assets/4407260/8000246/ba4b0984-0b75-11e5-8ec8-d53b1a0e1aae.PNG)

**Comment by Vivekban** [comment]
I have the same error, but goes when i copied libcurl.dll file into  C:/Ruby21/bin folder. If i didn't work try on 32-bit version(Ruby 2.1.6).

**Comment by chadrem** [comment]
@gowthamgts I'm looking at your last stack trace regarding the SSL error.  The second to last line shows you are using a gem called google_play_search version 0.0.12.  This is not my market_bot gem.  It also shows the error is being generated by the Net::HTTP library (market_bot doesn't use this library).  You have a couple options... one is to get certificate validation working right or the other is to disable it all together.
